scale: 1
metatile: 1
name: "Justice-Police"
bounds:
  - -5.14223839797325
  - 41.3332277729552
  - 9.56036371003871
  - 51.08984197105
center:
  - 2.37681
  - 48.84949
  - 18
format: "png"
minzoom: 5
maxzoom: 18
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
overlay:
  active: false
  opacity: 1
  position: -1
Stylesheet:
- "style.mss"
source: 'tms://localhost:3579/poi_commissariats_brigades+zonage_commissariats_brigades+zonage_tgi/{z}/{x}/{y}.mvt'
layers:
  - zonage_commissariats_brigades
  - zonage_tgi
  - poi_commissariats_brigades

